
# This docker-compose file is used as CI/CD pipeline to build and run the services in the docker container.

services:

  frontend:
    build:
      context: ./ci_proxy/.
    ports:
      - "80:80"
    restart: always
    networks:
      - local_network

  mongodb:
    image: mongo:latest
    restart: always
    expose:
      - "27017"
    env_file:
      - ../../.env
    networks:
      - local_network

  fastapi:
    build:
      context: ../../app/api/.
    depends_on:
      - mongodb
    expose:
      - "5678"
    volumes:
      - ./app/api:/app
    command: uvicorn app:app --host 0.0.0.0 --port 5678 --reload --workers 5 
    env_file:
      - ../../.env
    restart: always
    networks:
      - local_network

networks:
  local_network:
    driver: bridge
