services:

<<<<<<< HEAD
  frontend:
    build:
      context: ../../app/frontend/.
    ports:
      - "80:80"
    restart: always
    networks:
      - local_network

=======
>>>>>>> cf5c8d3c0425b6bd7abf78c0099d93a113749d1a
  mongodb:
    image: mongo:latest
    restart: always
    expose:
      - "27017"
    env_file:
      - ../../.env
    networks:
      - local_network

  fastapi:
    build:
      context: ../../app/api/.
    depends_on:
      - multi2vec-clip
      - mongodb
    expose:
      - "5678"
    volumes:
      - ./app/api:/app
    command: uvicorn app:app --host 0.0.0.0 --port 5678 --reload --workers 5 
    env_file:
      - ../../.env
    restart: always
    networks:
      - local_network

networks:
  local_network:
    driver: bridge
